version: 2
jobs:
  fetch_and_commit:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - checkout
      - run:
          command: |
            cp vacunas_covid.csv vacunas_covid-old.csv
            curl -o vacunas_covid.csv "https://cloud.minsa.gob.pe/s/ZgXoXqK2KLjRLxD/download"
            git add vacunas_covid.csv
            git config --global user.email "vacunasbot@example.com"
            git config --global user.name "Vacunasbot"
            sudo pip install csv-diff
            csv-diff vacunas_covid-old.csv vacunas_covid.csv --key=UUID > message.txt
            echo $'\n[skip ci]' >> message.txt
            git commit -F message.txt && \
              git push -q https://${GITHUB_PERSONAL_TOKEN}@github.com/annaabsi/git-scraper-vacunacion.git main \
              || true

workflows:
  version: 2
  build:
    jobs:
      - fetch_and_commit
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - main
    jobs:
      - fetch_and_commit
